const PathConstants = {
  HOME: "/",
  COUNTER: "/counter",
  PEOPLE: "/people",
  SALE_PAGE: "/sales",
  SALE_CRL_PAGE: "/sales/crl",
  SALE_CRL_MOR_PAGE: "/sales/crl/mor",
  SALE_CRL_PA_PAGE: "/sales/crl/pa",
  SALE_TPL_PAGE: "/sales/tpl",
  SALE_TPL_MOR_PAGE: "/sales/tpl/mor",
  SALE_TPL_PA_PAGE: "/sales/tpl/pa",
  POLICIES_PAGE: "/policies",
  POLICIES_CRL_PAGE: "/policies/crl",
  POLICIES_CRL_MOR_PAGE: "/policies/crl/mor",
  POLICIES_TPL_PAGE: "/policies/tpl",
  POLICIES_TPL_PA_PAGE: "/policies/tpl/pa",
  REPORT_PAGE: "/report",
  REPORT_CRL_PAGE: "/report/crl",
  REPORT_CRL_MOR_PAGE: "/report/crl/mor",
  REPORT_TPL_PAGE: "/report/tpl",
  REPORT_TPL_MOR_PAGE: "/report/tpl/mor",
  DASHBOARD: "/dashboard",
  HEALTH: "/health",
};

export default PathConstants;
