const fields = {
  hasBankLoan: "hasBankLoan",
  homeType: "homeType",
  homeUsing: "homeUsing",
  streetAddress: "streetAddress",
  provinceCode: "provinceCode",
  districtCode: "districtCode",
  communeCode: "communeCode",
  homeAddress: "homeAddress",
  homeValue: "homeValue",
  sumInsurance: "sumInsurance",
  homeAddon: "homeAddon",
  homeAddon2: "homeAddon2",
  durations: "durations",
  effectiveDate: "effectiveDate",
  expireDate: "expireDate",
  pkgCode: "pkgCode",
  isInsured: "isInsured",
  buyerIsCompany: "buyerIsCompany",
  buyerCifNumber: "buyerCifNumber",
  buyerName: "buyerName",
  buyerIdNo: "buyerIdNo",
  buyerDeputyName: "buyerDeputyName",
  buyerDeputyTitle: "buyerDeputyTitle",
  buyerAddress: "buyerAddress",
  buyerPhone: "buyerPhone",
  buyerEmail: "buyerEmail",
  buyerRelationship: "buyerRelationship",
  insuredName: "insuredName",
  insuredIdNo: "insuredIdNo",
  insuredPhone: "insuredPhone",
  insuredEmail: "insuredEmail",
  projectName: "projectName",
  saleType: "saleType",
  benIdNo: "benIdNo",
  benName: "benName",
  benAddress: "benAddress",
  beneficiaries: "beneficiaries",

  custName: "custName",
  custDob: "custDob",
  custID: "custID",
  custAddress: "custAddress",
  custEmail: "custEmail",
  custPhone: "custPhone",
  custGender: "custGender",
  creditNo: "creditNo",
  creditStartDate: "creditStartDate",
  creditEndDate: "creditEndDate",
  insStartDate: "insStartDate",
  insEndDate: "insEndDate",
  insAmount: "insAmount",
  creditAmount: "creditAmount",
  paymentMethod: "paymentMethod",
  discountCode: "discountCode",

  invoiceExport: "invoiceExport",
  invoiceIsCompany: "invoiceIsCompany",
  invoiceCompanyName: "invoiceCompanyName",
  invoiceBuyerName: "invoiceBuyerName",
  invoiceTaxCode: "invoiceTaxCode",
  invoiceEmail: "invoiceEmail",
  invoiceAddress: "invoiceAddress",

  confirmed: "confirmed",
  currentStepIndex: "currentStepIndex",
};

export default fields;
