const fields = {
  buyerName: "buyerName",
  buyerId: "buyerId",
  buyerAddress: "buyerAddress",
  buyerEmail: "buyerEmail",
  custName: "custName",
  custPhone: "custPhone",
  custEmail: "custEmail",
  custAddress: "custAddress",
  beginDate: "beginDate",
  pkgCode: "pkgCode",
  pkgCode2: "pkgCode2",
  custVgaId: "custVgaId",

  discountCode: "discountCode",
  discountCodeSubmit: "discountCodeSubmit",
  confirmed: "confirmed",
  paymentMethod: "paymentMethod",
  invoiceExport: "invoiceExport",
  invoiceIsCompany: "invoiceIsCompany",
  invoiceCompanyName: "invoiceCompanyName",
  invoiceBuyerName: "invoiceBuyerName",
  invoiceTaxCode: "invoiceTaxCode",
  invoiceEmail: "invoiceEmail",
  invoiceAddress: "invoiceAddress",
  countClickStep: "countClickStep",
  totalFee: "totalFee",
};

export default fields;
