const fields = {
  hasBankLoan: "hasBankLoan",
  loanContractNo: "loanContractNo",
  carUsing: "carUsing",
  carType: "carType",
  refSpecs: "refSpecs",
  carBrand: "carBrand",
  carBrandName: "carBrandName",
  carYear: "carYear",
  carLine: "carLine",
  carLineName: "carLineName",
  carVersion: "carVersion",
  carVersionName: "carVersionName",
  carSeat: "carSeat",
  carWeight: "carWeight",
  carPlateNo: "carPlateNo",
  ownerIsDriver: "ownerIsDriver",
  ownerGender: "ownerGender",
  ownerFullName: "ownerFullName",
  ownerBirthday: "ownerBirthday",
  ownerIdNo: "ownerIdNo",
  ownerPhoneNumber: "ownerPhoneNumber",
  ownerEmail: "ownerEmail",
  ownerAddress: "ownerAddress",
  ownerExperience: "ownerExperience",
  driverGender: "driverGender",
  driverExperience: "driverExperience",
  driverFullName: "driverFullName",
  driverBirthday: "driverBirthday",
  driverPhoneNumber: "driverPhoneNumber",
  activeRegionProvince: "activeRegionProvince",
  activeRegionProvinceName: "activeRegionProvinceName",
  duration: "duration",
  effectiveDate: "effectiveDate",
  effectiveDateTpl: "effectiveDateTpl",
  expireDate: "expireDate",
  carValue: "carValue",
  sumInsurance: "sumInsurance",
  deductibleExcess: "deductibleExcess",
  discountCode: "discountCode",
  callCheckDiscount: "callCheckDiscount",
  pkgCode: "pkgCode",
  carCaptureFrontLeft: "carCaptureFrontLeft",
  carCaptureFrontRight: "carCaptureFrontRight",
  carCaptureRearLeft: "carCaptureRearLeft",
  carCaptureRearRight: "carCaptureRearRight",
  confirmed: "confirmed",
  paymentMethod: "paymentMethod",
  saleCode: "saleCode",
  hasTplBundle: "hasTplBundle",
  tplTotalPremium: "tplTotalPremium",
  estCarValue: "estCarValue",
  coInsurances: "coInsurances",
  carNewPlateNoDate: "carNewPlateNoDate",
  carRegister: "carRegister",
  carChassisNo: "carChassisNo",
  carEngineNo: "carEngineNo",

  customerPhoneNumber: "customerPhoneNumber",

  callCreatePolicy: "callCreatePolicy",
  linkSendCustomer: "linkSendCustomer",
  carVersionChanged: "carVersionChanged",

  invoiceExport: "invoiceExport",
  invoiceIsCompany: "invoiceIsCompany",
  invoiceCompanyName: "invoiceCompanyName",
  invoiceBuyerName: "invoiceBuyerName",
  invoiceTaxCode: "invoiceTaxCode",
  invoiceEmail: "invoiceEmail",
  invoiceAddress: "invoiceAddress",

  over: "over",
  passLimitSumInsurance: "passLimitSumInsurance",
};

export default fields;
