const fields = {
  carUsing: "carUsing",
  deductibleExcess: "deductibleExcess",
  carType: "carType",
  refSpecs: "refSpecs",
  carBrand: "carBrand",
  carBrandDefault: "carBrandDefault",
  carYear: "carYear",
  carLine: "carLine",
  carVersion: "carVersion",
  carSeat: "carSeat",
  carWeight: "carWeight",
  ownerBirthday: "ownerBirthday",
  driverBirthday: "driverBirthday",
  driverExperience: "driverExperience",
  activeRegionProvince: "activeRegionProvince",
  duration: "duration",
  expireDate: "expireDate",
  effectiveDate: "effectiveDate",
  carValue: "carValue",
  sumInsurance: "sumInsurance",
  pkgCode: "pkgCode",
  carPlateNo: "carPlateNo",
  cityDataDefault: "cityDataDefault",
  feedbackInfoCar: "feedbackInfoCar",
};

export default fields;
