export const HOME_TYPE_DEPARTMENT = "APARTMENT_HOME";
export const HOME_TYPE_PRIVATE = "PRIVATE_HOME";
export const PKG_HOUSE_DEFAULT = "PKG_HOME_ND1";
export const PKG_APARTMENT_DEFAULT = "PKG_HOME_CC2";
export const DETAIL_COV_MAIN = "HOME_BASE_COVERAGES";
export const PROTECT_IN_HOUSE = "HOME_ASSET_INFO";
