const fields = {
  homeType: "homeType",
  departmentPkgCode: "departmentPkgCode",
  departmentPkgType: "departmentPkgType",
  homeBuildYear: "homeBuildYear",
  durations: "durations",
  effectiveDate: "effectiveDate",
  expireDate: "expireDate",
  homeValue: "homeValue",
  protectInHouse: "protectInHouse",
  homeAddon: "homeAddon",
  homeAddonMR: "homeAddonMR",
  discountCode: "discountCode",
  discountCodeSubmit: "discountCodeSubmit",
  buyerName: "buyerName",
  buyerPhone: "buyerPhone",
  buyerEmail: "buyerEmail",
  homeAddress: "homeAddress",
  city: "city",
  district: "district",
  ward: "ward",
  buyerRelationship: "buyerRelationship",
  confirmed: "confirmed",
  invoiceExport: "invoiceExport",
  invoiceIsCompany: "invoiceIsCompany",
  invoiceCompanyName: "invoiceCompanyName",
  invoiceBuyerName: "invoiceBuyerName",
  invoiceTaxCode: "invoiceTaxCode",
  invoiceEmail: "invoiceEmail",
  invoiceAddress: "invoiceAddress",
  paymentMethod: "paymentMethod",

  currentStep: "currentStep",
};

export default fields;
