const fields = {
  buyFor: "buyFor",
  duration: "duration",
  effectiveDate: "effectiveDate",
  expireDate: "expireDate",
  familyHas: "familyHas",
  pkgCode: "pkgCode",
  ownerFullName: "ownerFullName",
  ownerPhoneNumber: "ownerPhoneNumber",
  ownerIdNo: "ownerIdNo",
  ownerBirthday: "ownerBirthday",
  ownerEmail: "ownerEmail",
  insuredRelation: "insuredRelation",
  insuredFullName: "insuredFullName",
  insuredBirthday: "insuredBirthday",
  insuredIdNo: "insuredIdNo",
  insureds: "insureds",
  confirmed: "confirmed",
  totalFee: "totalFee",
  invoiceExport: "invoiceExport",
  invoiceIsCompany: "invoiceIsCompany",
  invoiceCompanyName: "invoiceCompanyName",
  invoiceBuyerName: "invoiceBuyerName",
  invoiceTaxCode: "invoiceTaxCode",
  invoiceEmail: "invoiceEmail",
  invoiceAddress: "invoiceAddress",
  paymentMethod: "paymentMethod",
  discountCode: "discountCode",
  fee: "fee",
  oldFee: "oldFee",
  discountCodeSubmit: "discountCodeSubmit",
};

export default fields;
